import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthContextProvider from "@/contexts/AuthContext";
import { TodoContextProvider } from "@/contexts/TodoContext";
import Header from "@/components/header";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-gray-900
         via-gray-800 to-gray-900 min-h-screen transition`}
      >
        <AuthContextProvider>
          <TodoContextProvider>
            <Header />
            {children}
            <Toaster toastOptions={{ duration: 3000 }} />
          </TodoContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
